bfsapp/urls.py
from django.urls import path
from .views import *

app_name='bfsapp'
urlpatterns = [

# admin side
    path('school-admin/logout/', AdminLogout.as_view(),
        name='adminlogout'),
    path('school-admin/login/', AdminLogin.as_view(),
        name='adminlogin'),
    path('school-admin/', AdminHomeView.as_view(), name='adminhome'),



    path('school-admin/videos/',
        AdminVideoListView.as_view(), name='adminvideolist'),
    path('school-admin/videos/create/',
        AdminVideoCreateView.as_view(), name='adminvideocreate'),
    path('school-admin/videos/<int:pk>/update/',
        AdminVideoUpdateView.as_view(), name='adminvideoupdate'),
    path('school-admin/videos/<int:pk>/delete/',
        AdminVideoDeleteView.as_view(), name='adminvideodelete'),



    path('school-admin/blogs/',
        AdminBlogListView.as_view(), name='adminbloglist'),
    path('school-admin/blogs/create/',
        AdminBlogCreateView.as_view(), name='adminblogcreate'),
    path('school-admin/blogs/<int:pk>/update/',
        AdminBlogUpdateView.as_view(), name='adminblogupdate'),
    path('school-admin/blogs/<int:pk>/delete/',
        AdminBlogDeleteView.as_view(), name='adminblogdelete'),

    path('school-admin/events/',
        AdminEventListView.as_view(), name='admineventlist'),
    path('school-admin/events/create/',
        AdminEventCreateView.as_view(), name='admineventcreate'),
    path('school-admin/events/<int:pk>/update/',
        AdminEventUpdateView.as_view(), name='admineventupdate'),
    path('school-admin/events/<int:pk>/delete/',
        AdminEventDeleteView.as_view(), name='admineventdelete'),

    path('school-admin/gallery/',
        AdminGalleryListView.as_view(), name='admingallerylist'),
    path('school-admin/gallery/create/',
        AdminGalleryCreateView.as_view(), name='admingallerycreate'),
    path('school-admin/gallery/<int:pk>/update/',
        AdminGalleryUpdateView.as_view(), name='admingalleryupdate'),
    path('school-admin/gallery/<int:pk>/delete/',
        AdminGalleryDeleteView.as_view(), name='admingallerydelete'),

    path('school-admin/notices/',
        AdminNoticeListView.as_view(), name='adminnoticelist'),
    path('school-admin/notices/create/',
        AdminNoticeCreateView.as_view(), name='adminnoticecreate'),
    path('school-admin/notices/<int:pk>/update/',
        AdminNoticeUpdateView.as_view(), name='adminnoticeupdate'),
    path('school-admin/notices/<int:pk>/delete/',
        AdminNoticeDeleteView.as_view(), name='adminnoticedelete'),

    path('school-admin/staffs/',
        AdminStaffListView.as_view(), name='adminstafflist'),
    path('school-admin/staffs/create/',
        AdminStaffCreateView.as_view(), name='adminstaffcreate'),
    path('school-admin/staffs/<int:pk>/update/',
        AdminStaffUpdateView.as_view(), name='adminstaffupdate'),
    path('school-admin/staffs/<int:pk>/delete/',
        AdminStaffDeleteView.as_view(), name='adminstaffdelete'),

    path('school-admin/testimonials/',
        AdminTestimonialListView.as_view(), name='admintestimoniallist'),
    path('school-admin/testimonials/create/',
        AdminTestimonialCreateView.as_view(), name='admintestimonialcreate'),
    path('school-admin/testimonials/<int:pk>/update/',
        AdminTestimonialUpdateView.as_view(), name='admintestimonialupdate'),
    path('school-admin/testimonials/<int:pk>/delete/',
        AdminTestimonialDeleteView.as_view(), name='admintestimonialdelete'),


    path('school-admin/activities/',
        AdminActivitiesListView.as_view(), name='adminactivitieslist'),
    path('school-admin/activities/create/',
        AdminActivitiesCreateView.as_view(), name='adminactivitiescreate'),
    path('school-admin/activities/<int:pk>/update/',
        AdminActivitiesUpdateView.as_view(), name='adminactivitiesupdate'),
    path('school-admin/activities/<int:pk>/delete/',
        AdminActivitiesDeleteView.as_view(), name='adminactivitiesdelete'),



    path('school-admin/features/',
        AdminFeaturesListView.as_view(), name='adminfeatureslist'),
    path('school-admin/features/create/',
        AdminFeaturesCreateView.as_view(), name='adminfeaturescreate'),
    path('school-admin/features/<int:pk>/update/',
        AdminFeaturesUpdateView.as_view(), name='adminfeaturesupdate'),
    path('school-admin/features/<int:pk>/delete/',
        AdminFeaturesDeleteView.as_view(), name='adminfeaturesdelete'),




    path('school-admin/services/',
        AdminServicesListView.as_view(), name='adminserviceslist'),
    path('school-admin/services/create/',
        AdminServicesCreateView.as_view(), name='adminservicescreate'),
    path('school-admin/services/<int:pk>/update/',
        AdminServicesUpdateView.as_view(), name='adminservicesupdate'),
    path('school-admin/services/<int:pk>/delete/',
        AdminServicesDeleteView.as_view(), name='adminservicesdelete'),



    path('school-admin/download/',
        AdminDownloadListView.as_view(), name='admindownloadlist'),
    path('school-admin/download/create/',
        AdminDownloadCreateView.as_view(), name='admindownloadcreate'),
    path('school-admin/download/<int:pk>/update/',
        AdminDownloadUpdateView.as_view(), name='admindownloadupdate'),
    path('school-admin/download/<int:pk>/delete/',
        AdminDownloadDeleteView.as_view(), name='admindownloaddelete'),



    path('school-admin/routine/',
        AdminRoutineListView.as_view(), name='adminroutinelist'),
    path('school-admin/routine/create/',
        AdminRoutineCreateView.as_view(), name='adminroutinecreate'),
    path('school-admin/routine/<int:pk>/update/',
        AdminRoutineUpdateView.as_view(), name='adminroutineupdate'),
    path('school-admin/routine/<int:pk>/delete/',
        AdminRoutineDeleteView.as_view(), name='adminroutinedelete'),




    path('school-admin/result/',
        AdminResultListView.as_view(), name='adminresultlist'),
    path('school-admin/result/create/',
        AdminResultCreateView.as_view(), name='adminresultcreate'),
    path('school-admin/result/<int:pk>/update/',
        AdminResultUpdateView.as_view(), name='adminresultupdate'),
    path('school-admin/result/<int:pk>/delete/',
        AdminResultDeleteView.as_view(), name='adminresultdelete'),



    path('school-admin/slider/',
        AdminSliderListView.as_view(), name='adminsliderlist'),
    path('school-admin/slider/create/',
        AdminSliderCreateView.as_view(), name='adminslidercreate'),
    path('school-admin/slider/<int:pk>/update/',
        AdminSliderUpdateView.as_view(), name='adminsliderupdate'),
    path('school-admin/slider/<int:pk>/delete/',
        AdminSliderDeleteView.as_view(), name='adminsliderdelete'), 



    path('school-admin/vacancii/',
        AdminVacanciiListView.as_view(), name='adminvacanciilist'),
    path('school-admin/vacancii/create/',
        AdminVacanciiCreateView.as_view(), name='adminvacanciicreate'),
    path('school-admin/vacancii/<int:pk>/update/',
        AdminVacanciiUpdateView.as_view(), name='adminvacanciiupdate'),
    path('school-admin/vacancii/<int:pk>/delete/',
        AdminVacanciiDeleteView.as_view(), name='adminvacanciidelete'),



    path('school-admin/price/',
        AdminPriceListView.as_view(), name='adminpricelist'),
    path('school-admin/price/create/',
        AdminPriceCreateView.as_view(), name='adminpricecreate'),
    path('school-admin/price/<int:pk>/update/',
        AdminPriceUpdateView.as_view(), name='adminpriceupdate'),
    path('school-admin/price/<int:pk>/delete/',
        AdminPriceDeleteView.as_view(), name='adminpricedelete'),
  




    path('school-admin/messages/',
        AdminMessageListView.as_view(), name='adminmessagelist'),
    path('school-admin/messages/<int:pk>/',
        AdminMessageDetailView.as_view(), name='adminmessagedetail'),
    path('school-admin/messages/<int:pk>/delete/',
        AdminMessageDeleteView.as_view(), name='adminmessagedelete'),



    path('school-admin/admission/',
        AdminAdmissionListView.as_view(), name='adminadmissionlist'),
    path('school-admin/admission/<int:pk>/',
        AdminAdmissionDetailView.as_view(), name='adminadmissiondetail'),
    path('school-admin/admission/<int:pk>/delete/',
        AdminAdmissionDeleteView.as_view(), name='adminadmissiondelete'),


    path('school-admin/vacancy/',
        AdminVacancyListView.as_view(), name='adminvacancylist'),
    path('school-admin/vacancy/<int:pk>/',
        AdminVacancyDetailView.as_view(), name='adminvacancydetail'),
    path('school-admin/vacancy/<int:pk>/delete/',
        AdminVacancyDeleteView.as_view(), name='adminvacancydelete'),

     







    # client side


    path('', ClientHomeView.as_view(), name='clienthome'),
	path('home', HomeView.as_view(), name='home'),
	path('about/', ClientAboutView.as_view(), name='clientabout'),
    path('service/', ClientServiceListView.as_view(), name='clientservicelist'),
	path('gallery/', ClientGalleryListView.as_view(), name='clientgallerylist'),
	path('blog/', ClientBlogListView.as_view(), name='clientbloglist'),
    path('blogs/<int:pk>/', ClientBlogDetailView.as_view(), name='clientblogdetail'),
	path('activities/', ClientActivitiesListView.as_view(), name='clientactivitieslist'),
    path('activiti/<int:pk>/', ClientActivitiesDetailView.as_view(), name='clientactivitiesdetail'),
    path('contact/', ClientContactView.as_view(), name='clientcontact'),
    path('events/<int:pk>/', ClientEventDetailView.as_view(), name='clienteventdetail'),
    path('admission/', ClientAdmissionView.as_view(), name='clientadmission'),
    path('admissionn/', ClientAdmissionnView.as_view(), name='clientadmissionn'),
    path('feestructure/', ClientFeestructureView.as_view(), name='clientfeestructure'),
    path('download/', ClientDownloadListView.as_view(), name='ClientdownloadList'),
    path('routine/', ClientRoutineListView.as_view(), name='Clientroutinelist'),
    path('result/', ClientResultListView.as_view(), name='Clientresultlist'),

bfsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bfsapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bfsapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User



class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()





class Blog(TimeStamp):
    title = models.CharField(max_length=500)
    image = models.ImageField(upload_to='blog/')
    content = models.TextField()
    author = models.CharField(max_length=200)

    def __str__(self):
        return self.title



class Video(TimeStamp):
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=255)


    def __str__(self):
        return self.title



class Event(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='event/')
    date = models.DateTimeField()
    location = models.CharField(max_length=300)


    def __str__(self):
        return self.title




class Notice(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title


class Staff(TimeStamp):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='staff/')
    post = models.CharField(max_length=100)
    phone1 = models.CharField(max_length=20, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    subject = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name



class Features(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='feature/')

    def __str__(self):
        return self.title



class Gallery(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title


class Slider(TimeStamp):
    image = models.ImageField(upload_to='slider/')
    caption = models.CharField(max_length=255)

    def __str__(self):
        return self.image.url


class Activities(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='activities/')
    date = models.DateTimeField()
    location = models.CharField(max_length=300)


    def __str__(self):
        return self.title


class Testimonial(TimeStamp):
    name = models.CharField(max_length=200)
    post = models.CharField(max_length=50)
    says = models.TextField()

    def __str__(self):
        return self.name


class Service(TimeStamp):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='service/', null=True, blank=True)
    content = models.TextField()

    def __str__(self):
        return self.title



class Download(TimeStamp):
    title = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/')
    content = models.TextField()
    image = models.ImageField(upload_to='service/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title


class Message(TimeStamp):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=15, null=True, blank=True)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.name



class Result(TimeStamp):
    grade = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/')

    def __str__(self):
        return self.grade


class Routine(TimeStamp):
    grade = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/')

    def __str__(self):
        return self.grade


class Admission(TimeStamp):
    name = models.CharField(max_length=255)
    birthdate =models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=15, null=True, blank=True)
    Applicant_PP_size_Photo = models.ImageField(null=True, blank=True, upload_to='admission/')
    Applicant_Marksheet_Photo = models.ImageField(null=True, blank=True, upload_to='admission/')
    grade = models.CharField(max_length=20, null=True, blank=True)
    percentage = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    muncipilaty = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    zipcode = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class Vacancy(TimeStamp):
    name = models.CharField(max_length=255)
    birthdate =models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=15, null=True, blank=True)
    Applicant_PP_size_Photo = models.ImageField(null=True, blank=True, upload_to='vacancy/')
    Applicant_Marksheet_Photo = models.ImageField(null=True, blank=True, upload_to='vacancy/')
    Qualification = models.CharField(max_length=20, null=True, blank=True)
    percentage = models.CharField(max_length=20)
    subject = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=100)
    muncipilaty = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    zipcode = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.name




class Vacancii(TimeStamp):
    title = models.TextField()
    content = models.TextField()


    def __str__(self):
        return self.title



class Price(TimeStamp):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.title

class A1(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A2(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A3(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A4(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A5(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A6(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A7(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A8(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title


    

templates/bfsapp/clienttemplates/ClientdownloadList.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block home %}active{% endblock home %}


{% block content %}
<br><br>
<div class="container">
	<div class="row">
		{% for download in downloads %}
		<div class="col-md-3">
			<div>
				<a href="{{download.document.url}}" download="">{{result.document}}<img src="{{download.image.url}}" class="img-responsive img-thumbnail"></a>
			</div>
			<div>
				<h4>{{download.title}}</h4><h5>{{download.uploaded_at}}</h5>
			</div>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock content %}

templates/bfsapp/clienttemplates/Clientresultlist.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block home %}active{% endblock home %}

{% block content %}
<br><br>

<style>
#customers {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

#customers td, #customers th {
    border: 1px solid #ddd;
    padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #4CAF50;
    color: white;
}
</style>
</head>
<body>
  <div class="container">
    <div class="student-grids">
      <div class="col-md-8 student-grid">
<center><h3 style="color: green"> Exam Result</h3></center><br>
<table id="customers">
  <tr>
    <th><h3>Class</h3></th>
    <th><h3>Download</h3></th>
     </tr>
  {% for result in results %}  
 
  <tr>
    <td>{{result.grade}}</td>
    <td><a href="{{result.document.url}}" download="">{{result.document}}</a></td>
  {% endfor %}
  </tr>
  
</table><br><br>
</div>
</div>
</div>



{% endblock content %}

templates/bfsapp/clienttemplates/clientabout.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block about %}active{% endblock about %}


{% block content %}

<div class="banner-w3agile">
			<div class="container">
				<h3><a href="">About</a></h3>
			</div>
		</div>
		<!--content-->
		<div class="content">
			<!--about-->
			<div class="about-w3">
				<div class="container">
					<h2 class="tittle">About Us</h2>
					<div class="about-grids">
						<div class="col-md-6 about-grid">
						 <h4>Think Now Think Ahead</h4>
							 <p>Bright Future English Boarding School was established in 2072 in Malangwa, Sarlahi with 120 students and 25 staff members. Initially, classes from Nursery to grade VII were offered. Today, it has become a full-fledged secondary school running classes from grade one to ten. Upon completion of the all construction of school complex at Malangwa-9, which is nearly 0.5 kilometers away from Bus-Station point on the Ring road</p>
							<p>The school has excellent infrastructure supported by state-of-the-art facilities. It has modern academic buildings with spacious classrooms, laboratories, conference hall, hostel buildings, administrative offices,  and playing grounds. There are separate buildings and rooms for extra-curricular activities such as Lab, e-class, Practicle, Activities, guitar, etc.	
							</p>
						 </div>
						<div class="col-md-6 video-grid">
							<iframe width="560" height="315" src="https://www.youtube.com/embed/GoKOhIzeakw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
			<!--about-->
			<!--What we do-->
				<div class="what-w3">
					<div class="container">
						<h3 class="tittle">What we do</h3>
						<div class="what-grids">
							<div class="col-md-6 what-grid">
						       {% for galleri in A7s %}
								<div class="mask">
									<img src="{{galleri.image.url}}" class="img-responsive zoom-img" />
								</div>
								{% endfor %}
								<div class="what-bottom">
									<h4>co-operative Environment</h4>
									<p>We believe that parents who send their children to The Radclyffe School have a clear idea of what we are trying to do for our students. To help students build on their strengths and overcome their weaknesses, To use the skills, knowledge, experience and talents of all staff to personalise the learning for each student.</p>
								</div>
							</div>
							<div class="col-md-6 what-grid">
								<div class="what-bottom1">
                                    <h4>Encourage Student at its Peak</h4>
									<p> Student encouragement is a student's desire to participate in the learning process. It is simply a student's willingness, need, desire, and compulsion to participate in, and be successful in the learning process.  Motivation is the key to a student's school success and is the driving force behind successful learning.</p>
								</div>
						       {% for galleri in A8s %}
								<div class="mask">
									<img src="{{galleri.image.url}}" class="img-responsive zoom-img" />
								</div>
								{% endfor %}
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			
						<div class="statistics-w3">
							<div class="container">
								<h3 class="tittle">Fun Facts</h3>
								<div class="statistics-grids">
									<div class="col-md-3 statistics-grid">
										<div class="statistic">
											<h5>Electronics Project</h5>
											<p>Our world are gather on full of electronics Connectivity, so we are perform the electronics practicle among the students to perform.
											</p>
										</div>
									</div>
									<div class="col-md-3 statistics-grid">
										<div class="statistic">
											<h5>Online Activities</h5>
											<p> “Students report positive and strong relations with these activities as Online exam, Online homework & and High Imagination thinking among each”</p>
										</div>
									</div>
									<div class="col-md-3 statistics-grid">
										<div class="statistic">
											<h4>80%</h4>
											<h5>Extra curriculum</h5>
											<p>All students should be able to find an extracurricular that they are interested in and can develop a passion for!</p>
										</div>
									</div>
									<div class="col-md-3 statistics-grid">
										<div class="statistic">
											<!-- <h4>100%</h4> -->
											<h5>MCQ Exam</h5><br>
											<p>The students of our school are practing in MCQ Exams everyday for their encourangement in study and basics </p>
										</div>
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>
<div class="content">
	<div class="projects-agile">
		<div class="container">
			<h2 class="tittle"> Videos</h2>
				{% for vide in video|slice:'12' %}					
					<div class="portfolio_grid_w3lss">
						<div class="col-md-4 w3agile_Projects_grid">
							<div class="w3agile_Projects_image">

								<iframe style="width: 360px; height: 230px" src="https://www.youtube.com/embed/{{vide.url}}?ecver=1" frameborder="0" allowfullscreen class="img-thumbnail"></iframe>

								<h3 style="color: green">{{vide.title}}</h3>
							</div>
						</div>
			</div>
			{% endfor %}	
			<div class="clearfix"> </div>
			<script type="text/javascript" src="js/smoothbox.jquery2.js"></script>
		</div>
	</div>
</div>
				

<div class="content">
	<div class="projects-agile">
		<div class="container">
					<h2 class="tittle">Our Staff</h2>
							{% for staff in staffs %}
							
						<div class="portfolio_grid_w3lss">

							<div class="col-md-4 w3agile_Projects_grid">
								<div class="w3agile_Projects_image">
										<figure>
											<img src="{{staff.image.url}}" alt="" class="img-responsive img-thumbnail"/>
											<figcaption>
											<h4>{{staff.name}}</h4>
											<p>Post: {{staff.post}}</p>
											<p>Email: {{staff.email}}</p>
											{% if staff.subject %}
											<p>Subject: {{staff.subject}}</p>
											{% endif %}
											{% if staff.phone1 %}
												<p>phone1: {{staff.phone1}}</p>
											{% endif %}

											</figcaption>
										</figure>
									</a>
								</div>
							</div>
						</div>
							{% endfor %}
						
						<div class="clearfix"> </div>
					<script type="text/javascript" src="js/smoothbox.jquery2.js"></script>
		</div>
	</div>
</div>



		

{% endblock content %}
                            {% for vide in video %}

								<iframe width="360" height="240" src="https://www.youtube.com/embed/{{vide.url}}?ecver=1" frameborder="0" allowfullscreen class="img-thumbnail"></iframe>
								<h3>{{vide.title}}</h3>

							{% endfor %}

templates/bfsapp/clienttemplates/clientbloglist.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block blog %}active{% endblock blog %}


{% block content %}

<div class="banner-w3agile">
			<div class="container">
				<h3><a href="">Blog</a></h3>
			</div>
		</div>

		<!--content-->
		<div class="content">
			<div class="courses-w3ls">
				<div class="container">
					<h2 class="tittle">Blogs</h2>
					{% for blog in blogs %}
					<div class="course-grids">
						<div class="col-md-3 course-grid">
							<div class="mask">
								<img src="{{blog.image.url}}" class="img-responsive zoom-img" />
							</div>
						</div>
						<div class="col-md-9 course-grid1 gri">
							<h4>{{blog.title}}</h4>
							<p>{{blog.content|truncatewords:'50'}}
                               <a class="btn btn-primary" href="{% url 'bfsapp:clientblogdetail' blog.id %}">Read More</a>
							</p>
							<p>Author:{{blog.author}}</p>
						
						</div>
						<div class="clearfix"></div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>	


{% endblock content %}

templates/bfsapp/clienttemplates/clientnotecalendar.html
{% extends 'bfsapp/clienttemplates/base.html' %}
{% load static %}
{% block home %}active{% endblock home %}

{% block content %}




{% endblock content %}

templates/bfsapp/clienttemplates/clientthankua.html
<!DOCTYPE html>
<html>
<head>
	<title>thanku</title>
</head>
<body style="background-color: lightgreen"><br><br><br><br><br><br>
<div class="container">
	<h1><center>Your Online Admission form has been<br> Successfully submitted</center></h1>
	<center><a href="{% url 'bfsapp:clienthome' %}"><button><h3>HOME</h3></button></a></center>
	<h1><center>We will Contact You SOON<br> Thanku !</center></h1>

</div>
</body>
</html>

templates/bfsapp/clienttemplates/resultlist.html
<!DOCTYPE html>
<html>
<head>
	<title>jjyt</title>
</head>
<body>
<h1>hello</h1>
</body>
</html>