bfsapp/urls.py
from django.urls import path
from .views import *

app_name='bfsapp'
urlpatterns = [

# admin side
    path('school-admin/logout/', AdminLogout.as_view(),
        name='adminlogout'),
    path('school-admin/login/', AdminLogin.as_view(),
        name='adminlogin'),
    path('school-admin/', AdminHomeView.as_view(), name='adminhome'),



    path('school-admin/videos/',
        AdminVideoListView.as_view(), name='adminvideolist'),
    path('school-admin/videos/create/',
        AdminVideoCreateView.as_view(), name='adminvideocreate'),
    path('school-admin/videos/<int:pk>/update/',
        AdminVideoUpdateView.as_view(), name='adminvideoupdate'),
    path('school-admin/videos/<int:pk>/delete/',
        AdminVideoDeleteView.as_view(), name='adminvideodelete'),



    path('school-admin/blogs/',
        AdminBlogListView.as_view(), name='adminbloglist'),
    path('school-admin/blogs/create/',
        AdminBlogCreateView.as_view(), name='adminblogcreate'),
    path('school-admin/blogs/<int:pk>/update/',
        AdminBlogUpdateView.as_view(), name='adminblogupdate'),
    path('school-admin/blogs/<int:pk>/delete/',
        AdminBlogDeleteView.as_view(), name='adminblogdelete'),

    path('school-admin/events/',
        AdminEventListView.as_view(), name='admineventlist'),
    path('school-admin/events/create/',
        AdminEventCreateView.as_view(), name='admineventcreate'),
    path('school-admin/events/<int:pk>/update/',
        AdminEventUpdateView.as_view(), name='admineventupdate'),
    path('school-admin/events/<int:pk>/delete/',
        AdminEventDeleteView.as_view(), name='admineventdelete'),

    path('school-admin/gallery/',
        AdminGalleryListView.as_view(), name='admingallerylist'),
    path('school-admin/gallery/create/',
        AdminGalleryCreateView.as_view(), name='admingallerycreate'),
    path('school-admin/gallery/<int:pk>/update/',
        AdminGalleryUpdateView.as_view(), name='admingalleryupdate'),
    path('school-admin/gallery/<int:pk>/delete/',
        AdminGalleryDeleteView.as_view(), name='admingallerydelete'),

    path('school-admin/notices/',
        AdminNoticeListView.as_view(), name='adminnoticelist'),
    path('school-admin/notices/create/',
        AdminNoticeCreateView.as_view(), name='adminnoticecreate'),
    path('school-admin/notices/<int:pk>/update/',
        AdminNoticeUpdateView.as_view(), name='adminnoticeupdate'),
    path('school-admin/notices/<int:pk>/delete/',
        AdminNoticeDeleteView.as_view(), name='adminnoticedelete'),

    path('school-admin/staffs/',
        AdminStaffListView.as_view(), name='adminstafflist'),
    path('school-admin/staffs/create/',
        AdminStaffCreateView.as_view(), name='adminstaffcreate'),
    path('school-admin/staffs/<int:pk>/update/',
        AdminStaffUpdateView.as_view(), name='adminstaffupdate'),
    path('school-admin/staffs/<int:pk>/delete/',
        AdminStaffDeleteView.as_view(), name='adminstaffdelete'),

    path('school-admin/testimonials/',
        AdminTestimonialListView.as_view(), name='admintestimoniallist'),
    path('school-admin/testimonials/create/',
        AdminTestimonialCreateView.as_view(), name='admintestimonialcreate'),
    path('school-admin/testimonials/<int:pk>/update/',
        AdminTestimonialUpdateView.as_view(), name='admintestimonialupdate'),
    path('school-admin/testimonials/<int:pk>/delete/',
        AdminTestimonialDeleteView.as_view(), name='admintestimonialdelete'),


    path('school-admin/activities/',
        AdminActivitiesListView.as_view(), name='adminactivitieslist'),
    path('school-admin/activities/create/',
        AdminActivitiesCreateView.as_view(), name='adminactivitiescreate'),
    path('school-admin/activities/<int:pk>/update/',
        AdminActivitiesUpdateView.as_view(), name='adminactivitiesupdate'),
    path('school-admin/activities/<int:pk>/delete/',
        AdminActivitiesDeleteView.as_view(), name='adminactivitiesdelete'),



    path('school-admin/features/',
        AdminFeaturesListView.as_view(), name='adminfeatureslist'),
    path('school-admin/features/create/',
        AdminFeaturesCreateView.as_view(), name='adminfeaturescreate'),
    path('school-admin/features/<int:pk>/update/',
        AdminFeaturesUpdateView.as_view(), name='adminfeaturesupdate'),
    path('school-admin/features/<int:pk>/delete/',
        AdminFeaturesDeleteView.as_view(), name='adminfeaturesdelete'),




    path('school-admin/services/',
        AdminServicesListView.as_view(), name='adminserviceslist'),
    path('school-admin/services/create/',
        AdminServicesCreateView.as_view(), name='adminservicescreate'),
    path('school-admin/services/<int:pk>/update/',
        AdminServicesUpdateView.as_view(), name='adminservicesupdate'),
    path('school-admin/services/<int:pk>/delete/',
        AdminServicesDeleteView.as_view(), name='adminservicesdelete'),



    path('school-admin/download/',
        AdminDownloadListView.as_view(), name='admindownloadlist'),
    path('school-admin/download/create/',
        AdminDownloadCreateView.as_view(), name='admindownloadcreate'),
    path('school-admin/download/<int:pk>/update/',
        AdminDownloadUpdateView.as_view(), name='admindownloadupdate'),
    path('school-admin/download/<int:pk>/delete/',
        AdminDownloadDeleteView.as_view(), name='admindownloaddelete'),



    path('school-admin/routine/',
        AdminRoutineListView.as_view(), name='adminroutinelist'),
    path('school-admin/routine/create/',
        AdminRoutineCreateView.as_view(), name='adminroutinecreate'),
    path('school-admin/routine/<int:pk>/update/',
        AdminRoutineUpdateView.as_view(), name='adminroutineupdate'),
    path('school-admin/routine/<int:pk>/delete/',
        AdminRoutineDeleteView.as_view(), name='adminroutinedelete'),




    path('school-admin/result/',
        AdminResultListView.as_view(), name='adminresultlist'),
    path('school-admin/result/create/',
        AdminResultCreateView.as_view(), name='adminresultcreate'),
    path('school-admin/result/<int:pk>/update/',
        AdminResultUpdateView.as_view(), name='adminresultupdate'),
    path('school-admin/result/<int:pk>/delete/',
        AdminResultDeleteView.as_view(), name='adminresultdelete'),



    path('school-admin/slider/',
        AdminSliderListView.as_view(), name='adminsliderlist'),
    path('school-admin/slider/create/',
        AdminSliderCreateView.as_view(), name='adminslidercreate'),
    path('school-admin/slider/<int:pk>/update/',
        AdminSliderUpdateView.as_view(), name='adminsliderupdate'),
    path('school-admin/slider/<int:pk>/delete/',
        AdminSliderDeleteView.as_view(), name='adminsliderdelete'), 



    path('school-admin/vacancii/',
        AdminVacanciiListView.as_view(), name='adminvacanciilist'),
    path('school-admin/vacancii/create/',
        AdminVacanciiCreateView.as_view(), name='adminvacanciicreate'),
    path('school-admin/vacancii/<int:pk>/update/',
        AdminVacanciiUpdateView.as_view(), name='adminvacanciiupdate'),
    path('school-admin/vacancii/<int:pk>/delete/',
        AdminVacanciiDeleteView.as_view(), name='adminvacanciidelete'),



    path('school-admin/price/',
        AdminPriceListView.as_view(), name='adminpricelist'),
    path('school-admin/price/create/',
        AdminPriceCreateView.as_view(), name='adminpricecreate'),
    path('school-admin/price/<int:pk>/update/',
        AdminPriceUpdateView.as_view(), name='adminpriceupdate'),
    path('school-admin/price/<int:pk>/delete/',
        AdminPriceDeleteView.as_view(), name='adminpricedelete'),
  




    path('school-admin/messages/',
        AdminMessageListView.as_view(), name='adminmessagelist'),
    path('school-admin/messages/<int:pk>/',
        AdminMessageDetailView.as_view(), name='adminmessagedetail'),
    path('school-admin/messages/<int:pk>/delete/',
        AdminMessageDeleteView.as_view(), name='adminmessagedelete'),



    path('school-admin/admission/',
        AdminAdmissionListView.as_view(), name='adminadmissionlist'),
    path('school-admin/admission/<int:pk>/',
        AdminAdmissionDetailView.as_view(), name='adminadmissiondetail'),
    path('school-admin/admission/<int:pk>/delete/',
        AdminAdmissionDeleteView.as_view(), name='adminadmissiondelete'),


    path('school-admin/vacancy/',
        AdminVacancyListView.as_view(), name='adminvacancylist'),
    path('school-admin/vacancy/<int:pk>/',
        AdminVacancyDetailView.as_view(), name='adminvacancydetail'),
    path('school-admin/vacancy/<int:pk>/delete/',
        AdminVacancyDeleteView.as_view(), name='adminvacancydelete'),

     







    # client side


    path('', ClientHomeView.as_view(), name='clienthome'),
	path('home', HomeView.as_view(), name='home'),
	path('about/', ClientAboutView.as_view(), name='clientabout'),
    path('service/', ClientServiceListView.as_view(), name='clientservicelist'),
	path('gallery/', ClientGalleryListView.as_view(), name='clientgallerylist'),
	path('blog/', ClientBlogListView.as_view(), name='clientbloglist'),
    path('blogs/<int:pk>/', ClientBlogDetailView.as_view(), name='clientblogdetail'),
	path('activities/', ClientActivitiesListView.as_view(), name='clientactivitieslist'),
    path('activiti/<int:pk>/', ClientActivitiesDetailView.as_view(), name='clientactivitiesdetail'),
    path('contact/', ClientContactView.as_view(), name='clientcontact'),
    path('events/<int:pk>/', ClientEventDetailView.as_view(), name='clienteventdetail'),
    path('admission/', ClientAdmissionView.as_view(), name='clientadmission'),
    path('admissionn/', ClientAdmissionnView.as_view(), name='clientadmissionn'),
    path('feestructure/', ClientFeestructureView.as_view(), name='clientfeestructure'),
    path('download/', ClientDownloadListView.as_view(), name='ClientdownloadList'),
    path('routine/', ClientRoutineListView.as_view(), name='Clientroutinelist'),
    path('result/', ClientResultListView.as_view(), name='Clientresultlist'),

bfsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bfsapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bfsapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User



class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()





class Blog(TimeStamp):
    title = models.CharField(max_length=500)
    image = models.ImageField(upload_to='blog/')
    content = models.TextField()
    author = models.CharField(max_length=200)

    def __str__(self):
        return self.title



class Video(TimeStamp):
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=255)


    def __str__(self):
        return self.title



class Event(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='event/')
    date = models.DateTimeField()
    location = models.CharField(max_length=300)


    def __str__(self):
        return self.title




class Notice(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title


class Staff(TimeStamp):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='staff/')
    post = models.CharField(max_length=100)
    phone1 = models.CharField(max_length=20, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    subject = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name



class Features(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='feature/')

    def __str__(self):
        return self.title



class Gallery(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title


class Slider(TimeStamp):
    image = models.ImageField(upload_to='slider/')
    caption = models.CharField(max_length=255)

    def __str__(self):
        return self.image.url


class Activities(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='activities/')
    date = models.DateTimeField()
    location = models.CharField(max_length=300)


    def __str__(self):
        return self.title


class Testimonial(TimeStamp):
    name = models.CharField(max_length=200)
    post = models.CharField(max_length=50)
    says = models.TextField()

    def __str__(self):
        return self.name


class Service(TimeStamp):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='service/', null=True, blank=True)
    content = models.TextField()

    def __str__(self):
        return self.title



class Download(TimeStamp):
    title = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/')
    content = models.TextField()
    image = models.ImageField(upload_to='service/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title


class Message(TimeStamp):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=15, null=True, blank=True)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.name



class Result(TimeStamp):
    grade = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/')

    def __str__(self):
        return self.grade


class Routine(TimeStamp):
    grade = models.CharField(max_length=100)
    document = models.FileField(upload_to='documents/')

    def __str__(self):
        return self.grade


class Admission(TimeStamp):
    name = models.CharField(max_length=255)
    birthdate =models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=15, null=True, blank=True)
    Applicant_PP_size_Photo = models.ImageField(null=True, blank=True, upload_to='admission/')
    Applicant_Marksheet_Photo = models.ImageField(null=True, blank=True, upload_to='admission/')
    grade = models.CharField(max_length=20, null=True, blank=True)
    percentage = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    muncipilaty = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    zipcode = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class Vacancy(TimeStamp):
    name = models.CharField(max_length=255)
    birthdate =models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=15, null=True, blank=True)
    Applicant_PP_size_Photo = models.ImageField(null=True, blank=True, upload_to='vacancy/')
    Applicant_Marksheet_Photo = models.ImageField(null=True, blank=True, upload_to='vacancy/')
    Qualification = models.CharField(max_length=20, null=True, blank=True)
    percentage = models.CharField(max_length=20)
    subject = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=100)
    muncipilaty = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    zipcode = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.name




class Vacancii(TimeStamp):
    title = models.TextField()
    content = models.TextField()


    def __str__(self):
        return self.title



class Price(TimeStamp):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.title

class A1(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A2(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A3(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A4(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A5(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A6(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A7(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

class A8(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title


    

templates/bfsapp/admintemplates/adminadmissiondelete.html
 <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h3 class="modal-title">Delete {{object.title}}</h3>
</div>
<form class="form" method="POST"  action="{% url 'bfsapp:adminadmissiondelete' object.id %}">{% csrf_token %}
    <div class="modal-body">
        Are you sure you want to delete {{object.title}}?
    </div>
    <div class="modal-footer">
        <button class="btn btn-danger">Delete</button>
        <button class="btn btn-default" data-dismiss="modal">Cancel</button>
    </div>
</form>

templates/bfsapp/admintemplates/adminsliderdelete.html
 <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h3 class="modal-title">Delete {{object.title}}</h3>
</div>
<form class="form" method="POST"  action="{% url 'bfsapp:adminsliderdelete' object.id %}">{% csrf_token %}
    <div class="modal-body">
        Are you sure you want to delete {{object.title}}?
    </div>
    <div class="modal-footer">
        <button class="btn btn-danger">Delete</button>
        <button class="btn btn-default" data-dismiss="modal">Cancel</button>
    </div>
</form>

templates/bfsapp/admintemplates/adminvacancydetail.html
{% extends 'bfsapp/admintemplates/base.html' %}
{% load static %}
{% block admissions %}active{% endblock admissions %}
{% block content %}
                <div id="page-wrapper">
                    <div style="background-color: #9AF7F4" class="graphs">
                         <div class="xs">


                    <body>
                            <div class="container-fluid">
                                <!-- Basic Examples -->
                                <div class="row clearfix">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="card">
                                            <div class="header">
                                                <h2>
                                                     Applicant Informations 
                                                </h2>
                                            </div>
	<h3>Applicant name: {{object.name}}</h3>
	{% if vacancy.Applicant_PP_size_Photo %}
	<h3>Applicant photo: <img src="{{vacancy.Applicant_PP_size_Photo.url}}" width="200"></h3>{% endif %}
	{% if vacancy.Applicant_Marksheet_Photo %}
	<h3>Applicant Marksheet photo: <img src="{{vacancy.Applicant_Marksheet_Photo.url}}" width="200"></h3>
	{% endif %}
	<h3>Date of Birth: {{object.birthdate}}</h3>
	<h3>Applicant phone no.: {{object.phone}}</h3>
	<h3>Applicant Email id: {{object.email}}</h3>
	<h3>Qualification: {{object.Qualification}}</h3>
	<h3>Percentage: {{object.percentage}}</h3>
	<h3>Subject: {{object.subject}}</h3>
	<h3>Address: {{object.address}}</h3>
	<h3>Muncipality: {{object.muncipilaty}}</h3>
	<h3>District: {{object.district}}</h3>
	<h3>Zipcode: {{object.zipcode}}</h3>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

{% endblock content %}

templates/bfsapp/admintemplates/base.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
<title>Admin</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Modern Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 <!-- Bootstrap Core CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<!-- file////// -->

<link href="{% static 'adminstatic/css/style.css' %}" rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<link href="{% static 'adminstatic/css/lines.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'adminstatic/css/font-awesome.css' %}" rel="stylesheet"> 
<!-- jQuery -->

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<!----webfonts--->
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
<!---//webfonts--->  
<!-- Nav CSS -->
<link href="{% static 'adminstatic/css/custom.css' %}" rel="stylesheet">
<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'adminstatic/js/metisMenu.min.js' %}"></script>
<script src="{% static 'adminstatic/js/custom.js' %}"></script>
<!-- Graph JavaScript -->
<script src="{% static 'adminstatic/js/d3.v3.js' %}"></script>
<script src="{% static 'adminstatic/js/rickshaw.js' %}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block extras %}

    {% endblock %}
</head>
<body>
<div id="wrapper">
     <!-- Navigation -->
        <nav class="top1 navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="#">Admin</a>
            </div>
            <div class="navbar-default sidebar" role="navigation">
		            <div class="col-md-12 widget widget1">
		        		<div class="r3_counter_box">
		                    <img src="{% static 'adminstatic/images/download.jpg' %}" alt=""/ style="max-width: 220px; margin: auto;">
		                    <div class="stats">
		                      <h5><strong>Engineer</strong></h5>
		                      <span>Ruppesh Adhikari</span>
		                    </div>
		                </div>
		        	</div>
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminhome' %}"><i class="fa fa-home fa-fw nav_icon"></i>Home</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminsliderlist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Slider</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminstafflist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Staff</a>
                        </li>

                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminactivitieslist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Activities</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminbloglist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Blog</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:admineventlist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Event</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminvideolist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Video</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminfeatureslist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Services</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:admingallerylist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Gallery</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:admintestimoniallist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Testimonial</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminvacanciilist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Post Vacancy</a>
                        </li>

                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminadmissionlist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Admission</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminvacancylist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Vacancy List</a>
                        </li>

                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:admindownloadlist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Download</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminmessagelist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Message</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminnoticelist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Notices</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminpricelist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Fee Structure</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminroutinelist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Routine</a>
                        </li>

                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminresultlist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Result</a>
                        </li>
                        <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminserviceslist' %}"><i class="fa fa-dashboard fa-fw nav_icon"></i>Features</a>
                        </li>




                            <li>
                            <a style="color: yellow" href="{% url 'bfsapp:adminlogout' %}">Logout</a>
                        	</li>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            {% block content %}


            {% endblock %}

            <div class="modal fade" id="schoolmodal" role="dialog">
			    <div class="modal-dialog">
			        <div class="modal-content">

			        </div>
			    </div>
			</div>
<br>
            <p style="color: yellow" class="text-center">Copyright &copy; 2018 Modern. All Rights Reserved | Design by <a href="/" target="_blank">Ruppesh Adhikari</a> </p>
		</div>
       </div>
      <!-- /#page-wrapper -->
   </div>
    <!-- /#wrapper -->
    <!-- Bootstrap Core JavaScript -->
        {% block javascript %}

    {% endblock javascript %}




</body>
</html>